css:
  - 'bundles/orofilter/lib/multiselect/jquery.multiselect.css'
  - 'bundles/orofilter/lib/multiselect/jquery.multiselect.filter.css'
  - 'bundles/orofilter/css/oro.filter.css'
js:
  - '@OroFilterBundle/Resources/public/lib/multiselect/jquery.multiselect.js'
  - '@OroFilterBundle/Resources/public/lib/multiselect/jquery.multiselect.filter.js'

  - '@OroFilterBundle/Resources/public/js/app/filter/formatter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/multiselectdecorator.js'

  - '@OroFilterBundle/Resources/public/js/app/filter/abstractfilter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/textfilter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/choicefilter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/numberfilter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/datefilter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/datetimefilter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/selectfilter.js'
  - '@OroFilterBundle/Resources/public/js/app/filter/multiselectfilter.js'

  - '@OroFilterBundle/Resources/public/js/app/filter/list.js'
