placeholders:
    scripts_before:
        items:
            filter_templates:
                order: 5
            filter_container:
                order: 20

items:
   filter_templates:
        template: OroFilterBundle:js:templates.html.twig
   filter_container:
        template: OroFilterBundle:Filter:container.js.twig
