parameters:
    oro_filter.extension.orm_filter.class:      Oro\Bundle\FilterBundle\Grid\Extension\OrmFilterExtension
    oro_filter.provider.datevarsprovider.class: Oro\Bundle\FilterBundle\Provider\DateModifierProvider

services:
    oro_filter.extension.orm_filter:
        class: %oro_filter.extension.orm_filter.class%
        arguments:
            - @oro_datagrid.datagrid.request_params
            - @translator
        tags:
            - { name: oro_datagrid.extension }

    oro_filter.provider.datemodifierprovider:
        class: %oro_filter.provider.datevarsprovider.class%
